spring:
  application:
    name: WashCarApi
  main:
    allow-bean-definition-overriding: true
server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://118.190.132.99:8761/eureka/  #注册中心的地址